name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: DeterminateSystems/flake-checker-action@v7

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - run: nix develop -c prettier -w .
      - run: nix fmt .
      - uses: EndBug/add-and-commit@v9
        with:
          message: "chore: lint"
          default_author: github_actions
